### ISSUE TITLE
[Bug] Oneflow, onediff with pytorch 2.4.1 ImportError: libcudnn_cnn_infer.so.8

### ISSUE THREAD

**Issue by liho00** [siliconflow/onediff#1125]
### Your current environment information

Traceback (most recent call last):
  File "/home/shadeform/miniconda3/envs/miner/lib/python3.10/site-packages/onediff/utils/import_utils.py", line 16, in check_module_availability
    importlib.import_module(module_name)
  File "/home/shadeform/miniconda3/envs/miner/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/shadeform/miniconda3/envs/miner/lib/python3.10/site-packages/oneflow/__init__.py", line 26, in <module>
    import oneflow._oneflow_internal
ImportError: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory

### 🐛 Describe the bug

onediff==1.2.1.dev24+g9231f556
pytorch==2.4.1

python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu118
python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu121
python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu122
tried above three oneflow installation.

seems like oneflow not supporting pytorch==2.4.1, if i install pytorch==2.3.1 then it works

**Comment by strint** [comment]
What is the cudnn version are you using?

You can get it with:
```
import torch

if torch.backends.cudnn.is_available():
    cudnn_version = torch.backends.cudnn.version()
    print(f"cuDNN version: {cudnn_version}")
else:
    print("cuDNN is not available.")
```

**Comment by techzuhaib** [comment]
This worked for me: sudo apt install libcudnn8

**Comment by strint** [comment]
```
python3 -m pip install nvidia-cudnn-cu11==8.7.0.84
```
Can fix this.

**Comment by liho00** [comment]
> ```
> python3 -m pip install nvidia-cudnn-cu11==8.7.0.84
> ```
> 
> can fix this.

after running this python3 -m pip install nvidia-cudnn-cu11==8.7.0.84
i got below error
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory

**Comment by strint** [comment]
> libcudnn.so.9

which package is reporting this error

**Comment by liho00** [comment]
> > libcudnn.so.9
> 
> which package is reporting this error

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.4.1 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 8.9.7.29 which is incompatible.

**Comment by liho00** [comment]
> This worked for me: sudo apt install libcudnn8

sudo apt install libcudnn8
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libcudnn8


+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.12              Driver Version: 550.90.12      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:07:00.0 Off |                    0 |
| N/A   24C    P0             69W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          On  |   00000000:08:00.0 Off |                    0 |
| N/A   26C    P0             69W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |

**Comment by marigoold** [comment]
@liho00 
try
```
pip install nvidia-cudnn-cu12==8.9.0.131
```
